#!/bin/sh

#--------------------------------------------------------------------
# Homebrew Utilities
#--------------------------------------------------------------------

case "$fn" in

    # Update Homebrew and installed packages
    "brew:update")
        echo "Atualizando o Homebrew e seus pacotes instalados ..."
        if [ "$echocommand" == "true" ]; then
            echo "${GREEN}brew update; brew upgrade; brew cask upgrade; brew cleanup;\n${NC}"
        fi
        brew update; brew upgrade; brew cask upgrade; brew cleanup;
    ;;

esac
