#!/bin/sh

#--------------------------------------------------------------------
# LAMP (Linux, Apache, MySQL, PHP)
#--------------------------------------------------------------------
if [ "$mysql_password" != "none" ]; then
    mysql_password_arg="${mysql_password_arg}"
else
    mysql_password_arg=""
fi

case "$fn" in

    # abrir sequel pro ou troque os diretorios para o dbmaneger que mais lhe agradar
    "mysql")

        if [ "$echocommand" == "true" ]; then
            echo "${GREEN}open -a /Applications/Sequel\ Pro.app\n\n${NC}"
        fi
        open -a /Applications/Sequel\ Pro.app
    ;;


    # Open MySQL CLI
    "mysql:cli")

        if [ "$echocommand" == "true" ]; then
            if [ "$mysql_socket" != "" ]; then
                echo "${GREEN}mycli ${GRAY}-u${mysql_user} ${mysql_password_arg} ${GREEN} -S $mysql_socket\n\n${NC}"
            else
                echo "${GREEN}mycli ${GRAY}-u${mysql_user} ${mysql_password_arg} ${GREEN} \n\n${NC}"
            fi
            
        fi
        if [ "$mysql_socket" != "" ]; then
            mycli  -u$mysql_user $mysql_password_arg -S $mysql_socket
        else
            mycli  -u$mysql_user $mysql_password_arg
        fi
    ;;


    # Dump all MySQL databases
    "mysql:export-all")

        if [ "$echocommand" == "true" ]; then
            echo "${GREEN}${mysqldump} -u ${mysql_user} -p ${mysql_password} --all-databases > all-database.sql\n\n${NC}"
        fi
        ${mysqldump} -u ${mysql_user} ${mysql_password_arg} --all-databases > all-database.sql
    ;;


    # Export MySQL database
    "mysql:dump")

        echo "Insira o nome do arquivo para salvar o banco de dados compactado : "

        if [ ! -z "$firstParameter" -a "$firstParameter" != " " ]; then
            read filename

            if [ ! -z "$filename" -a "$filename" != " " ]; then
                if [ "$echocommand" == "true" ]; then
                    echo "${GREEN}$mysql --host=localhost ${GRAY}-u${mysql_user} ${mysql_password_arg}${GREEN} | pv | gzip -c > ${GRAY}'${filename}'.sql.gz\n\n${NC}"
                fi
                $mysqldump -u"$mysql_user" "$mysql_password_arg" $firstParameter | pv | gzip -c > "$filename".sql.gz
            else
                "Por favor, especifique o nome do arquivo"
            fi
        else
            echo "Especifique o banco de dados para exportar"
            echo "Ex .: mysql:export database"
        fi
    ;;


    # List all MySQL databases
    "mysql:list")

        if [ "$echocommand" == "true" ]; then
            echo "${GREEN}echo 'show databases;' | ${mysql} ${GRAY} -u${mysql_user} ${mysql_password_arg} ${databasename}\n\n${NC}"
        fi
        echo "show databases;" | ${mysql} -u${mysql_user} ${mysql_password_arg}
    ;;


    # Import MySQL database
    "mysql:import")

        echo "Digite o nome do banco de dados para importar o arquivo SQL selecionado: "

        if [ ! -z "$firstParameter" -a "$firstParameter" != " " ]; then
            read databasename

            if [ ! -z "$databasename" -a "$databasename" != " " ]; then
                if [ "$echocommand" == "true" ]; then
                    echo "${GREEN}pv ${GRAY}${firstParameter}${GREEN} | ${mysql} ${GRAY} -u${mysql_user} ${mysql_password_arg} ${databasename}\n\n${NC}"
                fi
                pv $firstParameter | $mysql -u"$mysql_user" "$mysql_password_arg" $databasename
            else
                "por favo especifique o nome do banco de dados"
            fi
        else
            echo "Especifique o arquivo .SQL a ser importado"
            echo "Ex .: mysql:import /path/to/file.sql"
        fi
    ;;


    # Export all MySQL databases
    "mysql:dump-all")

        databases=`$mysql -u"$mysql_user" "$mysql_password_arg" -e "SHOW DATABASES;" | tr -d "| " | grep -v Database`

        for db in $databases; do
            if [[ "$db" != "information_schema" ]] && [[ "$db" != "performance_schema" ]] && [[ "$db" != "mysql" ]] && [[ "$db" != _* ]] ; then
                echo "Dumping database: $db"
                $mysqldump -u"$mysql_user" "$mysql_password_arg" --databases $db > `date +%Y%m%d`.$db.sql
            fi
        done
    ;;


    # Import single MySQL database table
    "mysql:import-table")

        echo "Digite o nome do banco de dados que contém a tabela a ser importada: "

        if [ ! -z "$firstParameter" -a "$firstParameter" != " " ]; then
            read databasename

            if [ ! -z "$databasename" -a "$databasename" != " " ]; then
                if [ "$echocommand" == "true" ]; then
                    echo "${GREEN}pv ${GRAY}${firstParameter}${GREEN} | ${mysql} ${GRAY} -u ${mysql_user} -D ${databasename}\n\n${NC}"
                fi
                pv $firstParameter | $mysql -u $mysql_user -p -D $databasename
            else
                "Especifique o nome do banco de dados"
            fi
        else
            echo "Especifique o arquivo SQL que contém a única tabela a ser importada"
            echo "Ex: mysql:import /path/to/file.sql"
        fi
    ;;


    # Create MySQL database
    "mysql:create")

        if [ ! -z "$firstParameter" -a "$firstParameter" != " " ]; then
            if [ "$echocommand" == "true" ]; then
                echo "${GREEN}echo 'create database ${GRAY}${firstParameter}'${GREEN} | ${mysql} ${GRAY} -u${mysql_user} ${mysql_password_arg} ${databasename}\n\n${NC}"
            fi
            echo "create database ${firstParameter}" | ${mysql} -u${mysql_user} ${mysql_password_arg}
        else
            echo "Insira o nome do novo Banco de dados"
            echo "Ex .: mysql:create database-name"
        fi
    ;;


    # Remove MySQL database
    "mysql:drop")

        if [ ! -z "$firstParameter" -a "$firstParameter" != " " ]; then
            if [ "$echocommand" == "true" ]; then
                echo "${GREEN}echo 'drop database ${GRAY}${firstParameter}'${GREEN} | ${mysql} ${GRAY} -u${mysql_user} ${mysql_password_arg} ${databasename}\n\n${NC}"
            fi
            echo "drop database ${firstParameter}" | ${mysql} -u${mysql_user} ${mysql_password_arg}
        else
            echo "insira o nome do Banco de dados que deseja remover"
            echo "E.g.: mysql:drop database-name"
        fi
    ;;


    # Duplicate MySQL database
    "mysql:duplicate")

        echo "Insira o nome da nova tabela: "

        if [ ! -z "$firstParameter" -a "$firstParameter" != " " ]; then
            read databasename

            if [ ! -z "$databasename" -a "$databasename" != " " ]; then
                if [ "$echocommand" == "true" ]; then
                    echo "${GREEN}mac mysql:create ${GRAY}$databasename${GREEN} && $mysqldump -u${mysql_user} ${mysql_password_arg} ${GRAY}${firstParameter}${GREEN} | ${mysql} -u${mysql_user} ${mysql_password_arg} ${GRAY}${databasename}\n\n${NC}"
                fi
                mac mysql:create $databasename && $mysqldump -u${mysql_user} ${mysql_password_arg} $firstParameter | $mysql -u${mysql_user} ${mysql_password_arg} $databasename
            else
                "insira o nome do banco de dados"
            fi
        else
            echo "Especifique o nome do banco de dados para duplicar"
            echo "Ex .: mysql:remove database-name"
        fi
    ;;


    # Start MAMP Apache and MySQL
    "mamp:start")

        # Ask for password up-front
        sudo -v
        # Open MAMP
        open /Applications/MAMP\ PRO/MAMP\ PRO.app/
        # Start Apache
        sudo /Applications/MAMP/Library/bin/httpd -f "/Library/Application Support/appsolute/MAMP PRO/conf/httpd.conf" -k start
        # Start MySQL
        sh -c '/Applications/MAMP/Library/bin/mysqld_safe --defaults-file=/Applications/MAMP/tmp/mysql/my.cnf --port=3306 --socket=/Applications/MAMP/tmp/mysql/mysql.sock --user=gabriel --pid-file=/Applications/MAMP/tmp/mysql/mysql.pid --log-error=/Applications/MAMP/logs/mysql_error_log.err --tmpdir=/Applications/MAMP/tmp/mysql/tmpdir --datadir=/Library/Application\ Support/appsolute/MAMP\ PRO/db/mysql &'
    ;;


    # Start MAMP Apache and MySQL
    "mamp:stop")

        # Ask for password up-front
        sudo -v
        # Open MAMP
        open /Applications/MAMP\ PRO/MAMP\ PRO.app/
        # Stop Apache
        sudo /Applications/MAMP/Library/bin/httpd -f "/Library/Application Support/appsolute/MAMP PRO/conf/httpd.conf" -k stop
        # Stop MySQL
        sh -c '/Applications/MAMP/Library/bin/mysqladmin -u root -proot --socket=/Applications/MAMP/tmp/mysql/mysql.sock shutdown'
    ;;


    # Restart MAMP Apache and MySQL
    "mamp:restart")

        # Ask for password up-front
        sudo -v
        # Open MAMP
        open /Applications/MAMP\ PRO/MAMP\ PRO.app/
        # Stop Apache
        sudo /Applications/MAMP/Library/bin/httpd -f "/Library/Application Support/appsolute/MAMP PRO/conf/httpd.conf" -k stop
        # Stop MySQL
        sh -c '/Applications/MAMP/Library/bin/mysqladmin -u root -proot --socket=/Applications/MAMP/tmp/mysql/mysql.sock shutdown'
        # Start Apache
        sudo /Applications/MAMP/Library/bin/httpd -f "/Library/Application Support/appsolute/MAMP PRO/conf/httpd.conf" -k start
        # Start MySQL
        sh -c '/Applications/MAMP/Library/bin/mysqld_safe --defaults-file=/Applications/MAMP/tmp/mysql/my.cnf --port=3306 --socket=/Applications/MAMP/tmp/mysql/mysql.sock --user=gabriel --pid-file=/Applications/MAMP/tmp/mysql/mysql.pid --log-error=/Applications/MAMP/logs/mysql_error_log.err --tmpdir=/Applications/MAMP/tmp/mysql/tmpdir --datadir=/Library/Application\ Support/appsolute/MAMP\ PRO/db/mysql &'
    ;;


    # Check PHP syntax in current directory
    "php:syntax")

        if [ "$echocommand" == "true" ]; then
            echo "${GREEN}find . -name \*.php -exec php -l '{}' \;\n\n${NC}"
        fi
        echo "Checking PHP syntax for all files in current location..."
        find . -name \*.php -exec php -l "{}" \;
    ;;


    # Get PHP info
    "php:info")

        if [ "$echocommand" == "true" ]; then
            echo "${GREEN}$php -i\n\n${NC}"
        fi
        $php -i
    ;;

esac
