#!/bin/sh

#--------------------------------------------------------------------
# Performance and maintenance Utilities
#--------------------------------------------------------------------

case "$fn" in

    # Get overall system information
    "system")

        if [ "$echocommand" == "true" ]; then
            echo "${GREEN}glances \n\n${NC}"
        fi

        glances
    ;;


    # Show temperature, fan and battery statistics
    "temp")

        if [ ! -f /usr/local/bin/istats ]; then
            read -r -p "Deseja instalar iStats utility? (https://github.com/Chris911/iStats) (Yes / No)" response
            case $response in
                [yY][eE][sS]|[yY])
                    sudo gem install iStats -n/usr/local/bin
                    ;;
                *)
                    exit
                    ;;
            esac
        else
            if [ "$echocommand" == "true" ]; then
                echo "${GREEN}istats all \n\n${NC}"
            fi
            istats all
        fi
    ;;


    # See memory usage sorted by memory consumption
    "memory")

        if [ "$echocommand" == "true" ]; then
            echo "${GREEN}top -o MEM \n\n${NC}"
        fi
        top -o MEM
    ;;


    # Empty trash
    "trash:empty")

        if [ "$echocommand" == "true" ]; then
            echo "${GREEN}sudo rm -rf ~/.Trash/* \n\n${NC}"
        fi
        sudo rm -rf ~/.Trash/*
    ;;


    # Calculate trash size
    "trash:size")

        if [ "$echocommand" == "true" ]; then
            echo "${GREEN}du -sh ~/.Trash/ \n\n${NC}"
        fi
        echo "Trash size: "
        du -sh ~/.Trash/
    ;;


    # Remove all files and directories from Desktop directory
    "desktop:cleanup")

        if [ "$echocommand" == "true" ]; then
            echo "${GREEN}du -sh ~/.Trash/ \n\n${NC}"
        fi
        echo "Estes são os arquivos e diretórios que estão localizados atualmente na área de trabalho: "
        ls -lat ~/Desktop/
        echo "\n============================================="
        read -r -p "Você deseja remover todo o conteúdo do diretório Desktop? (Yes / No)" response
        case $response in
            [yY][eE][sS]|[yY])
                rm -rf ~/Desktop/*
                ;;
            *)
                exit
                ;;
        esac
    ;;


    # Remove all files and directories from Downloads directory
    "downloads:cleanup")

        if [ "$echocommand" == "true" ]; then
            echo "${GREEN}du -sh ~/.Trash/ \n\n${NC}"
        fi
        echo "Estes são os arquivos e diretórios que estão localizados atualmente em Downloads: "
        ls -lat ~/Downloads/
        echo "\n============================================="
        read -r -p "Você deseja remover todo o conteúdo do diretório de Downloads? (Yes / No)" response
        case $response in
            [yY][eE][sS]|[yY])
                rm -rf ~/Downloads/*
                ;;
            *)
                exit
                ;;
        esac
    ;;

esac